### ISSUE TITLE
Undefined variable $utilities-links-underline when use sass files

### ISSUE THREAD

**Issue by ghost** [themeselection/materio-bootstrap-html-admin-template-free#1]
Error: Undefined variable.
    ╷
639 │           $utilities-links-underline,
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  resources/scss/vendors/materio/scss/_bootstrap-extended/_utilities.scss 639:11  @import
  resources/scss/vendors/materio/scss/_bootstrap-extended.scss 7:9                @import
  resources/scss/vendors/materio/scss/core.scss 2:9

**Comment by SHVM-09** [comment]
Hi [benvxavier](https://github.com/benvxavier),

I trust this message finds you well.

Upon reviewing the latest package, it seems there are no reported errors when changes are made to SCSS. To ensure you have the most up-to-date version, please download the latest package from [here](https://themeselection.com/item/materio-free-bootstrap-html-admin-template/) and make sure you are using the latest Bootstrap version, 5.3.2.

If the issue persists even after updating, could you kindly share more details such as reproduction steps, code snippets, or screenshots? This will enable me to investigate the problem more thoroughly and provide you with the best possible assistance.

Feel free to reach out if you encounter any further issues. :+1:

Best regards,
