### ISSUE TITLE
Changing color for the whole theme is not working

### ISSUE THREAD

**Issue by yassinehamzaoui** [themeselection/materio-bootstrap-html-admin-template-free#2]
### Steps to reproduce

change the $black and $body-bg variables under the _variables scss file 

### What is expected?

changing the theme colors

### What is actually happening?

colors of theme didn't change

### Additional data

manually used

**Comment by yassinehamzaoui** [comment]
any help ?

**Comment by yassinehamzaoui** [comment]
Hello guys, any updates please ?

**Comment by SHVM-09** [comment]
Hi [yassinehamzaoui](https://github.com/yassinehamzaoui),

Thank you for your patience and for choosing our template.

To customize the colors according to your requirements, you can follow these steps:

Locate the `theme-default.scss` file in the `/scss` directory.
Make the necessary changes to the color variables as indicated in the image below:
[Include image or reference to color variables]

Demo Change : (explanatory purpose only)

![Screenshot 2023-12-27 at 7 00 17 PM](https://github.com/themeselection/materio-bootstrap-html-admin-template-free/assets/110282392/bef68404-7cc6-445a-81fc-22b3c5849e5f)

Demo Output: (explanatory purpose only)
![Screenshot 2023-12-27 at 7 00 33 PM](https://github.com/themeselection/materio-bootstrap-html-admin-template-free/assets/110282392/fc26b007-e73d-462f-a36c-3c10917600ec)

After making the changes, run the yarn build command. Ensure that your project is being served locally using the yarn serve command (refer [docs](https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation/installation-build.html)). Your custom color changes should now be reflected in the template.

I hope this helps answer your question. Please feel free to reach out if you have any further questions or concerns.

Best regards,
